# Generated by Django 6.0.1 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_dashboard_status_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
