# Generated by Django 6.0.1 on 2026-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='off_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
