# Generated by Django 6.0.1 on 2026-04-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_user_off_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('waiting', 'Waiting for approval'), ('reviewed', 'Reviewed'), ('paid', 'Payment sent'), ('rejected', 'Rejected'), ('withdrawal_fail', 'Withdrawal Failed')], default='processing', max_length=20),
        ),
    ]
